### ISSUE TITLE
window_sum in stft is just a constant?

### ISSUE THREAD

**Issue by xiaoyangnihao** [rishikksh20/iSTFTNet-pytorch#7]
I print the window_sum in stft, line: 155， find that the value will a constant, except for the former and latter padding positions. the window function only plays the role of linear scaling. Does this result meet the windowing expectations?

**Comment by aqtq314** [comment]
Recall that during forward STFT, frames are multiplied with a window function. These windows have often overlaps and they don't necessarily sum up to 1 at a certain sample position. This means that during inverse STFT, we need to rescale each sample with the sum of all occurred windows. Hence the window_sum function.

In the specific case of Hann window, their overlapping sum is a constant because of the nature of raised cosine function. Try with a window other than Hann (like Hamming window or None for rectangular window) and you'll see that it's no longer the same value everywhere, but more of a periodic scaler.

**Comment by xiaoyangnihao** [comment]
> 
I tried Hamming window instead, the window_sum value is also a constant. I think the reason is we choose 'fftbins=True' in line 'win_sq = get_window(window, win_length, fftbins=True)', so it will create a "periodic" window, not a "symmetric" window.

**Comment by aqtq314** [comment]
Just took an in-depth look and it seems like all cosine-sum windows (like hann, hamming, blackman) can turn flat given a small enough hop_size. I was thinking non-zero endpoints in hamming window could cause some kind of bumping periodically but turns out it only does that with larger hop_sizes :sweat_smile:
![output](https://user-images.githubusercontent.com/3953866/174589513-14cc005d-3ffd-43b4-a8c6-c00f325f3a8a.png)
![output2](https://user-images.githubusercontent.com/3953866/174589636-36501049-1d58-4980-9d8b-1c8f5de737cb.png)
